import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { buttonVariants } from "~/components/ui/button";
import { ArrowBigRight } from "lucide-react";
import { Consume } from "~/components/ui/con-sume";
import { cn } from "~/utils/ui/cn";
import { mediaTypeIcons } from "~/components/resources/mediaTypeIcon";
import dynamic from "next/dynamic";

const DEFAULT_COLORS: [string, string] = ["#3b82f6", "#76b9ce"];
const gradientColors = DEFAULT_COLORS;

const gradientStyle = `linear-gradient(to right, ${gradientColors[0]}, ${gradientColors[1]})`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CONSUME</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-row"
        style={{ backgroundImage: gradientStyle }}
      >
        <div className="m-3 flex min-h-full w-full rounded-md bg-background">
          <div className="m-auto flex flex-row gap-32">
            {/* BACKGROUND */}
            <BackgroundMediaTypes />

            {/* LEFT */}
            <div className="z-10 mb-8 flex w-[25vw] flex-col justify-center gap-4">
              <div className="font-mono text-sm text-muted-foreground">
                Made by @yonisku
              </div>
              <div className="tracking-light text-3xl font-semibold">
                A list that helps you <strong>consume</strong> your favorite content
              </div>
            </div>

            {/* RIGHT */}
            <Link
              href="/board"
              className={cn(
                buttonVariants({ variant: "secondary" }),
                "z-10 flex h-72 w-[35vw] flex-col justify-around p-16"
              )}
            >
              <div className="flex flex-row items-center gap-4">
                <strong className="text-6xl">
                  <Consume />
                </strong>
                <ArrowBigRight
                  className="mt-2"
                  size="3.5rem"
                  style={{ color: "#66AADA" }}
                />
              </div>
              <div className="text-2xl font-black">Go to your consume board</div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

const BackgroundMediaTypes = dynamic(
  () =>
    Promise.resolve(() => {
      return (
        <div>
          {Array(20)
            .fill(0)
            .map((_, i) => {
              const RandomIcon =
                mediaTypeIcons[Math.floor(Math.random() * mediaTypeIcons.length)];
              if (!RandomIcon) {
                return null;
              }
              return (
                <div
                  key={i}
                  className="absolute z-0 h-24 w-24 rounded-full object-contain"
                  style={{
                    opacity: 0.15,
                    top: `${Math.random() * 95}%`,
                    left: `${Math.random() * 95}%`,
                  }}
                >
                  <RandomIcon size={64} />
                </div>
              );
            })}
        </div>
      );
    }),
  {
    ssr: false,
  }
);

export default Home;
