import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { Button } from "~/components/ui/button";
import { ArrowBigRight } from "lucide-react";
import { Consume } from "~/components/ui/con-sume";

const DEFAULT_COLORS: [string, string] = ["#3b82f6", "#76b9ce"];
const gradientColors = DEFAULT_COLORS;

const gradientStyle = `linear-gradient(to right, ${gradientColors[0]}, ${gradientColors[1]})`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CONSUME</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-row"
        style={{ backgroundImage: gradientStyle }}
      >
        <div className="m-3 flex min-h-full w-full rounded-md bg-background">
          <div className="m-auto flex flex-row gap-32">
            {/* LEFT */}
            <div className="mb-8 flex w-[25vw] flex-col justify-center gap-4">
              <div className="font-mono text-sm text-muted-foreground">
                Made by @yonisku
              </div>
              <div className="tracking-light text-3xl font-semibold">
                A list that helps you <strong>consume</strong> your favorite content
              </div>
            </div>

            {/* RIGHT */}
            <Link href="/board">
              <Button
                className="flex h-72 w-[35vw] flex-col justify-around p-16"
                variant="secondary"
              >
                <div className="flex flex-row items-center gap-4">
                  <strong className="text-6xl">
                    <Consume />
                  </strong>
                  <ArrowBigRight
                    className="mt-2"
                    size="3.5rem"
                    style={{ color: "#66AADA" }}
                  />
                </div>
                <div className="text-2xl font-black">Go to your consume board</div>
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  // const { data: secretMessage } = api.example.getSecretMessage.useQuery(
  //   undefined, // no input
  //   { enabled: sessionData?.user !== undefined }
  // );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {/* {secretMessage && <span> - {secretMessage}</span>} */}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
